/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d76c4b3979a02ffed496b43e09e21a14)
interface __BaseEnv_Env {
	CODEX_LINKS: KVNamespace;
	CODEX_PACKAGES: R2Bucket;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
