/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ace5141d1ff120c88218900107c760d6)
interface __BaseEnv_Env {
	CODEX_LINKS: KVNamespace;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
